### ISSUE TITLE
Train Tiago in multiple tasks

### ISSUE THREAD

**Issue by michalvavrecka** [incognite-lab/myGym#15]
Check the Tiago URDF (compare to iGibson Tiago) and try to train the robot in basic configs  (reach, push, Pnp). Let the body fixed, use only one arm in action space.

**Comment by gabinsane** [comment]
Tiago reach (joints and step control)
![Screenshot from 2023-11-02 16-55-19](https://github.com/incognite-lab/myGym/assets/38910946/a8686ada-a167-400d-bf7a-17e858dd1b52)
![Screenshot from 2023-11-02 16-55-55](https://github.com/incognite-lab/myGym/assets/38910946/9c11b6da-dc57-4965-bac3-e469087c33e9)

**Comment by gabinsane** [comment]
tiago pnp_3n (joints and step control)
![Screenshot from 2023-11-02 16-46-31](https://github.com/incognite-lab/myGym/assets/38910946/3b583df5-2c47-4c64-becd-edaec32060f0)


![Screenshot from 2023-11-02 16-53-50](https://github.com/incognite-lab/myGym/assets/38910946/5a0f0279-3fc3-4012-b549-fcfd25098497)
